name: Rclone sync
description: Sync files so S3 using Rclone


inputs:
  s3-endpoint:
    description: Required input set S3 endpoint
    required: true
  s3-access-key-id:
    description: Required input set S3 access key id
    required: true
  s3-secret-access-key:
    description: Required input set S3 secret access key
    required: true
  destination-path:
    description: Required input to set destination path
    required: true
  source-path:
    description: Optional input to set source path
    required: false
    default: '.'


runs:
  using: composite
  steps:
    - name: Sync to S3
      uses: docker://docker.io/rclone/rclone:1.67
      with:
        args: "sync ${{ inputs.source-path }} s3:${{ inputs.destination-path }} --s3-acl=public-read --fast-list --checksum --update --use-server-modtime --metadata --inplace --delete-during"
      env:
        RCLONE_CONFIG_S3_TYPE: s3
        RCLONE_CONFIG_S3_PROVIDER: Other
        RCLONE_CONFIG_S3_ENDPOINT: ${{ inputs.s3-endpoint }}
        RCLONE_CONFIG_S3_ACCESS_KEY_ID: ${{ inputs.s3-access-key-id }}
        RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ${{ inputs.s3-secret-access-key }}
