name: "Reusable workflow: publish basemap vector"

on:
  workflow_call:
    inputs:
      s3-endpoint:
        description: Required input to set S3 endpoint
        type: string
        required: true
      archive-version:
        description: Optional input to set PMTiles archive version
        type: string
        default: 0.0.0
      stable:
        description: Optional input to set if publish is stable
        type: boolean
        default: false

    secrets:
      s3-access-key-id:
        description: S3 access key id
        required: true
      s3-secret-access-key:
        description: S3 secret access key
        required: true

jobs:
  generate-basemap-vector-pmtiles:
    name: PMTiles to S3
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Change version
        uses: dschanoeh/change-property@v1
        with:
          file: vector/config.properties
          property: archive_version
          value: ${{ inputs.archive-version }}

      - name: Generate PMTiles
        uses: ./.github/actions/basemap-vector-generate-pmtiles

      - name: Upload PMTiles to S3
        uses: ./.github/actions/rclone-sync
        with:
          s3-endpoint: ${{ inputs.s3-endpoint }}
          s3-access-key-id: ${{ secrets.s3-access-key-id }}
          s3-secret-access-key: ${{ secrets.s3-secret-access-key }}
          source-path: vector/data/output
          destination-path: /tiles/vector/pmtiles

      - name: Upload PMTiles to GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: vector/data/output/lithuania.pmtiles

  publish-basemap-vector-martin-docker-image:
    name: Martin docker image build and push
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.docker.outputs.digest }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Change version
        uses: dschanoeh/change-property@v1
        with:
          file: vector/config.properties
          property: archive_version
          value: ${{ inputs.archive-version }}

      - name: Build & tag docker image
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        id: docker
        with:
          docker-image: ghcr.io/govlt/national-basemap-vector-martin
          docker-context: .
          file: vector/docker/Dockerfile
          environment: ${{ inputs.stable && 'stable' ||  'preview' }}
          no-cache: true
          push: true
          cache-from: ''
          cache-to: ''

  generate-basemap-vector-mvt:
    name: Generate Mapbox vector tiles
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    needs:
      - publish-basemap-vector-martin-docker-image
      - generate-basemap-vector-pmtiles
    services:
      martin:
        image: ghcr.io/govlt/national-basemap-vector-martin@${{ needs.publish-basemap-vector-martin-docker-image.outputs.digest }}
        ports:
          - 3000:3000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: vector-basemap-pmtiles
          merge-multiple: true

      - name: Get all zxy combinations
        run: gunzip -c lithuania.pmtiles.layerstats.tsv.gz | awk -F'\t' '{print $1 "\t" $2 "\t" $3}' | uniq > zxy.tsv

      - name: Generate tiles.json
        run: curl http://localhost:3000/vector --create-dirs -o "tiles/tile.json" --compressed -s -S

      - name: Change tiles url
        run: jq --compact-output '.tiles = ["'"${TILES}"'"]' tile.json > tile.json.tmp && mv tile.json.tmp tile.json
        working-directory: tiles
        env:
          TILES: http://localhost:80/{z}/{x}/{y}.pbf

      - name: Generate Mapbox vector tiles
        run: tail -n +2 zxy.tsv | parallel --colsep '\t' curl "http://localhost:3000/vector/{1}/{2}/{3}" --create-dirs -s -S -o "tiles/{1}/{2}/{3}.pbf" --compressed

      - name: Generate glyphs
        uses: ./.github/actions/build-pbf-glyphs
        with:
          output-directory: tiles/font

      - name: Generate sprites
        uses: ./.github/actions/build-sprites
        with:
          output-directory: tiles/sprite

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: tiles
          name: mvt-tiles

  s3-upload-basemap-vector-mvt:
    name: S3 upload vector basemap Mapbox vector tiles
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: generate-basemap-vector-mvt
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mvt-tiles
          path: tiles
          merge-multiple: true

      - name: Create tiles archive
        run: zip -r tiles.zip tiles

      - name: Upload to S3
        uses: govlt/national-basemap/.github/actions/rclone-sync@main
        with:
          s3-endpoint: ${{ inputs.s3-endpoint }}
          s3-access-key-id: ${{ secrets.s3-access-key-id }}
          s3-secret-access-key: ${{ secrets.s3-secret-access-key }}
          source-path: tiles.zip
          destination-path: /tiles/vector/mvt

      - name: Upload tiles to GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tiles.zip
          make_latest: true

  build-basemap-vector-github-pages:
    name: Build GitHub pages
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: generate-basemap-vector-mvt
    if: inputs.stable
    permissions:
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mvt-tiles
          path: tiles
          merge-multiple: true

      - name: Change tiles url
        run: jq --compact-output '.tiles = ["'"${TILES}"'"]' tile.json > tile.json.tmp && mv tile.json.tmp tile.json
        working-directory: tiles
        env:
          TILES: https://vector-github.startupgov.lt/{z}/{x}/{y}.pbf

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./tiles

  publish-basemap-vector-github-pages:
    name: Publish GitHub pages
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: inputs.stable
    needs: build-basemap-vector-github-pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish-basemap-vector-docker-image:
    name: Vector docker image build and push
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: generate-basemap-vector-mvt
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: mvt-tiles
          path: vector/docker/static/tiles
          merge-multiple: true

      - name: Build & tag docker image
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        with:
          docker-image: ghcr.io/govlt/national-basemap-vector
          docker-context: vector/docker/static
          file: vector/docker/static/Dockerfile
          environment: ${{ inputs.stable && 'stable' ||  'preview' }}
          no-cache: true
          push: true
          cache-from: ''
          cache-to: ''
